#!/bin/sh

#-
# Copyright 2013-2014 Emmanuel Vadot <elbarto@bocal.org>
# All rights reserved
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted providing that the following conditions 
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

usage() {
cat <<EOF
Usage: `basename $0` section key value
EOF

exit 0
}

error() {
    echo $1
    exit 1
}

key_exists() {
    grep "${KEY}=" /etc/sysconfig/${SECTION} >/dev/null
    if [ $? -ne 0 ]; then
        return 1
    fi

    return 0
}

section_exists() {
    if [ ! -f /etc/sysconfig/${SECTION} ]; then
        return 1
    fi

    return 0
}

value_set() {
    sed -i.bak "s/\(${KEY}\)=.*/\1=${VALUE}/" /etc/sysconfig/${SECTION}
}

if [ $# -ne 3 ]; then
    usage
fi

SECTION=$1
shift
KEY=$1
shift
VALUE=$1
shift

section_exists  error "Section '${SECTION}' doesn't exists"
key_exists || error "Key '${KEY}' doesn't exists in section '${SECTION}'"
value_set
